### PR TITLE
Adding code to run on Powersystem

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by puzrin** [comment]
Close as useless

**Comment by genisysram** [comment]
This package is actually part of Ubuntu 20.04 - we are trying to ensure that users of the ppc64le distributions have perfect parity with Intel distributions. We don't know who the specific users are but this is probably a somewhat commonly used package on these distros.

**Comment by puzrin** [comment]
This package uses pure js and has no platform dependencies. I see no reasons why ppc64le should be tested separate.

**Comment by genisysram** [comment]
Its for ppc64le users to give confidence that it can work on your repository .

**Comment by puzrin** [comment]
That's NOT binary package. If you wish to do multiplatform testing for JS - do it outside please.

**Comment by genisysram** [comment]
Thank you

**Pull request closed without merging**
