### PR TITLE
Fix underscore.string ReDos in 0.1.x branch

### PR DESCRIPTION
**Pull request by paulirish**
Hiya.

I work on Modernizr: https://github.com/Modernizr/Modernizr/issues/2396
...which depends on Remarkable: https://github.com/jonschlinkert/remarkable/pull/312
...which depends on argparse. :)

Packages upstream from you are [being flagged with a vulnerability](https://snyk.io/vuln/npm:underscore.string:20170908), which is creating all sorts of noise. (Obviously, you're not at fault, but you know.. it happens...)

Modern argparse moved to lodash and doesn't have this issue anymore. However, some maintainers would [prefer a patch version](https://github.com/jonschlinkert/remarkable/pull/312#issuecomment-447502661) instead of upgrading to a major release and worrying about other compatibility changes.

I made the necessary changes from your last 0.1.x patch release and tests look good.
**Would you be open to shipping a 0.1.17 npm package with this change?**
(I suppose it would make sense merge into a v0.1.x branch in your repo, but that's up to you. :)

Thank you!

cc @jonschlinkert @mschipperheyn @rejas @foolip

### CODE REVIEW

**Comment by puzrin** [comment]
@paulirish would you consider switch to https://github.com/markdown-it/markdown-it instead? Remarkable is very outdated itself.

**Comment by rejas** [comment]
Thanks for recommendation @puzrin I created a PR for that at Modernizr

**Comment by paulirish** [comment]
> @paulirish would you consider switch to markdown-it/markdown-it instead? 

I mean... sure. 😕

...

But stepping back, this issue has involved quite a bunch of people, all spending time to investigate this and get to a resolution. (I haven't been involved with Modernizr in years, but I got pulled in and am trying to do the right thing here)

Is it reasonable that @jonschlinkert prefers a patch version bump to resolve a security vulnerability? Kind of a pain in the neck, but sure.. it's reasonable.
Is it reasonable for you to suggest a better markdown parser? It doesn't solve this problem for other transitive depdendents of old argparse, but.. it's reasonable.

Anyway.. it's been a while since I've been slightly frustrated by open source, so I guess today's the day. :)  

Cheers, guys.

**Comment by puzrin** [comment]
Even maintained projects have EOL for old versions. I don't like to create patch for 5 years old release, that's not normal.

**Comment by uiteoi** [comment]
I think the main issue is that remarkable is relying on on a pre-1.0 version of argparse, which was a development release according to semver. Security patches should be provided for non-development releases.

This has indeed been very frustrating for many months, mostly from remarkable's maintainer. So I have finally decided to switch to markdown-it for toubkal, which was very easy.

So thanks for the suggestion.

**Pull request closed without merging**
