### PR TITLE
fix: use '=' in args

### PR DESCRIPTION
**Pull request by CatWithApple**
Fix error in parse '--examplepath="C:\myfolder\env=x64" '.

### CODE REVIEW

**Comment by puzrin** [comment]
Could you add test?

**Comment by lddubeau** [comment]
Is there something I can do to help getting this fix into the next release?

**Comment by puzrin** [comment]
Released. Sorry for delay - i missed notification about PR update.

**Comment by lddubeau** [comment]
Many thanks!

**Pull request merged**
